version: '2.4'

services:
  nodejsutil:
    build: 
      dockerfile: Dockerfile
      context: ./
    container_name: nodejsutil
    env_file:
      - env_file
    volumes:
      - ../../:/home/node/projects
    working_dir: /home/node
    entrypoint: tail
    command: -f /dev/null